name: Container build
on: push
jobs:
  build_image:
    runs-on: container-builder
    environment: Production
    steps:
    - uses: actions/checkout@v4
    - name: Build container image
      run: |
        ./scripts/build.sh --name ${{ vars.IMAGE_NAME }} --version latest --build-file-path "./Dockerfile"
  start_container:
    runs-on: container-builder
    environment: Production
    steps:
    - uses: actions/checkout@v4
    - name: Start container
      run: |
        ./scripts/start.sh --name ${{ vars.CONTAINER_NAME }} --image ${{ vars.IMAGE_NAME }} --version latest