name: Container build
on: push
jobs:
  build_image:
    runs-on: container-builder
    steps:
    - name: Build container image
      run: |
        ./scripts/build.sh --name ${IMAGE_NAME} --version latest --build-file-path "./Dockerfile"
  start_container:
    runs-on: container-builder
    steps:
    - name: Start container
      run: |
        ./scripts/start.sh --name ${CONTAINER_NAME} --image ${IMAGE_NAME} --version latest