name: Container build
on: push
jobs:
  build_image:
    runs-on: container-builder
    environment: Production
    steps:
    - uses: actions/checkout@v4
    - name: Build container image
      run: |
        ./scripts/build.sh --name ${{ vars.IMAGE_NAME }} --version latest --build-file-path "./Dockerfile"
  deploy_image:
    runs-on: container-builder
    environment: Production
    steps:
    - uses: actions/checkout@v4
    - name: Deploy container image
      run: |
        ./scripts/deploy.sh --name ${{ vars.IMAGE_NAME }} --version latest --registry ${{ vars.REGISTRY_GITHUB_URI }} --registry-username ${{ secrets.REGISTRY_GITHUB_USERNAME }} --registry-password ${{ secrets.REGISTRY_GITHUB_PASSWORD }}
  start_container:
    runs-on: container-builder
    environment: Production
    needs: build_image
    steps:
    - uses: actions/checkout@v4
    - name: Start container
      env:
        RUNNER_DISPLAY_NAME: ${{ vars.RUNNER_DISPLAY_NAME }}
        RUNNER_URL: ${{ vars.RUNNER_URL }}
        RUNNER_GROUP: ${{ vars.RUNNER_GROUP }}
        RUNNER_TOKEN: ${{ secrets.RUNNER_TOKEN }}
      run: |
        ./scripts/start.sh --name ${{ vars.CONTAINER_NAME }} --image ${{ vars.IMAGE_NAME }} --version latest